# Generated by Django 2.1.5 on 2019-05-15 16:47

from django.db import migrations
import topnotchdev.files_widget.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20190511_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=topnotchdev.files_widget.fields.ImagesField(default='post_pics/default.jpg'),
        ),
    ]
